const GET_TEMPLATE_MESSAGE = 'ChatTemplate/GET_TEMPLATE_MESSAGE'
const GET_TEMPLATE_MESSAGE_FAIL = 'ChatTemplate/GET_TEMPLATE_MESSAGE_FAIL'
const GET_TEMPLATE_MESSAGE_SUCCESS = 'ChatTemplate/GET_TEMPLATE_MESSAGE_SUCCESS'

const SEND_TEMPLATE_MESSAGE = 'ChatTemplate/SEND_TEMPLATE_MESSAGE'
const SEND_TEMPLATE_MESSAGE_FAIL = 'ChatTemplate/SEND_TEMPLATE_MESSAGE_FAIL'
const SEND_TEMPLATE_MESSAGE_SUCCESS = 'ChatTemplate/SEND_TEMPLATE_MESSAGE_SUCCESS'


export {
  GET_TEMPLATE_MESSAGE,
  GET_TEMPLATE_MESSAGE_FAIL,
  GET_TEMPLATE_MESSAGE_SUCCESS,
  SEND_TEMPLATE_MESSAGE,
  SEND_TEMPLATE_MESSAGE_FAIL,
  SEND_TEMPLATE_MESSAGE_SUCCESS
}